name: Pepperoni Workflow
on:
  workflow_dispatch:

jobs:
  A_setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1 

  B_build: 
    needs: A_setup
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: WordPress Hosted on EC2

    - name: Terraform Format
      run: terraform fmt
      working-directory: WordPress Hosted on EC2

    - name: Terraform Validate
      run: terraform validate
      working-directory: WordPress Hosted on EC2

    - name: Terraform Plan
      run: terraform plan
      working-directory: WordPress Hosted on EC2

    - name: Terraform Apply
      run: terraform apply -auto-approve 
      working-directory: WordPress Hosted on EC2
        
    - name: Terraform Refresh
      run: terraform refresh 
      working-directory: WordPress Hosted on EC2
      
    - name: Terraform Output
      run: |
        echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        echo "bh_public_ip=$(terraform output -raw bh_public_ip)" >> $GITHUB_ENV
        echo "setup_server_private_key=$(terraform output -raw setup_server_private_key)" >> $GITHUB_ENV
        echo "efs_id=$(terraform output -raw efs_id)" >> $GITHUB_ENV
        
      working-directory: WordPress Hosted on EC2

  C_install_gh_cli:
    needs: B_build
    runs-on: ubuntu-latest
    steps:
    - name: Install GitHub CLI
      run: |
        # Install GitHub CLI on the remote server
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
        sudo apt update
        sudo apt install gh

  D_authenticate_gh_cli:
    needs: C_install_gh_cli
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate GitHub CLI
      run: |
        gh auth login --with-token <<< ${{ secrets.GH_TOKEN }}

  E_configure_EC2_instance:
    needs: D_authenticate_gh_cli
    runs-on: ubuntu-latest
    steps:
    - name: SSH into Setup Server, Mount EFS and Upload Docker Resources Folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ needs.B_build.outputs.public_ip }}
        username: ec2-user
        key: ${{ needs.B_build.outputs.setup_server_private_key }}
        script: |
          git clone https://github.com/AlexTNewell/tech-test.git
          sudo yum install -y amazon-efs-utils
          mkdir -p /var/www/docker_resources
          echo "${{ needs.B_build.outputs.efs_id }}"
          sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport "${{ needs.B_build.outputs.efs_id }}":/ /var/www/docker_resources
          sudo cp -r /home/ec2-user/tech-test/* /var/www/docker_resources
