name: Deployment Workflow
on:
  workflow_dispatch:

jobs:
  A_setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1 

  B_build: 
    needs: A_setup
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: WordPress Hosted on EC2

    - name: Terraform Format
      run: terraform fmt
      working-directory: WordPress Hosted on EC2

    - name: Terraform Validate
      run: terraform validate
      working-directory: WordPress Hosted on EC2

    - name: Terraform Plan
      run: terraform plan
      working-directory: WordPress Hosted on EC2

    - name: Terraform Apply
      run: terraform apply -auto-approve 
      working-directory: WordPress Hosted on EC2
        
    

